runtime: python39
entrypoint: gunicorn -b :$PORT check_system_back.wsgi

instance_class: F2

env_variables:
  DJANGO_SETTINGS_MODULE: "check_system_back.settings"

automatic_scaling:
  target_cpu_utilization: 0.75